console.log '    _____________________'
console.log '   /                   / \\        z'
console.log '  /                   /   \\      z'
console.log ' /                   /     \\    z'
console.log '/                   /       \\  z'
console.log '___________________/---------\\'
console.log '"                 "'
