(write-line "    _____________________")
(write-line "   /                   / \\        z")
(write-line "  /                   /   \\      z")
(write-line " /                   /     \\    z")
(write-line "/                   /       \\  z")
(write-line "___________________/---------\\")
(write-line "                 ")
