print("    _____________________\n")
print("   /                   / \\        z\n")
print("  /                   /   \\      z\n")
print(" /                   /     \\    z\n")
print("/                   /       \\  z\n")
print("___________________/---------\\\n")
print("                 ")
